import { generateSecret, generateURI, verify } from "otplib";
import QRCode from "qrcode";

/**
 * Mandatory second factor for Teacher / Departmental Admin / Super Admin
 * logins — see design doc §9. Deliberately TOTP, not SMS (SIM-swap risk).
 *
 * NOTE on totpSecretEncrypted (schema field name): in this scaffold the
 * secret is stored as generated by otplib (base32, not yet encrypted at
 * rest). Before production, wrap it with an application-level encryption
 * step (e.g. AES-GCM using a key from a secrets manager) rather than
 * storing the raw secret — flagged clearly in HANDOFF.md "Known gaps."
 *
 * otplib v13 uses a functional, options-object API (generateSecret /
 * generateURI / generate / verify) rather than the older singleton
 * `authenticator` object from earlier otplib versions — worth knowing if
 * you're used to the v12 API from other projects/tutorials.
 */

export function generateTotpSecret(): string {
  return generateSecret();
}

export function getTotpEnrollmentUri(secret: string, accountLabel: string, issuer: string): string {
  return generateURI({ secret, label: accountLabel, issuer });
}

export async function getTotpQrDataUrl(otpauthUri: string): Promise<string> {
  return QRCode.toDataURL(otpauthUri, { margin: 1, width: 220 });
}

export async function verifyTotpCode(secret: string, token: string): Promise<boolean> {
  try {
    const result = await verify({ secret, token });
    return result.valid;
  } catch {
    return false;
  }
}
